eureka:
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://localhost:8761/eureka
spring:
 data:
   mongodb:
   # username: ${MONGO_USER}
     #password: ${MONGO_PASSWORD}
     database: ${MONGO_DATABASE}
     port: ${MONGO_PORT}     
     host: ${MONGO_HOST}
     #database: favrecipe
     #port: 27017
     #host: localhost
server:
 port: 8081

#spring:
 #data:
  #  mongodb:
   #  username: ${MONGO_USER}
    # password: ${MONGO_PASSWORD}
     #database: ${MONGO_DATABASE}
     #port: ${MONGO_PORT}
     #host: ${MONGO_HOST}
#server:
 #port: 8083
 

 

