FROM openjdk:16-alpine3.13
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} favouriteservice-1.0.jar
ENV MONGO_HOST=mongodb://localhost:27017
ENV MONGO_DATABASE=userprofile5
ENV MONGO_PORT=27017
ENTRYPOINT ["java","-jar","favouriteservice-1.0.jar"]